version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:22.0.4
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # üåç URL public cho browser
      KC_HOSTNAME_URL: http://localhost:8080
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
      
    networks:
      - nbva-network
    volumes:
      - keycloak-data:/opt/keycloak/data
      
volumes:
  keycloak-data:
networks:
  nbva-network:
    external: true