server:
  port: 8085
  servlet:
    context-path: /payment-service

spring:
  application:
      name: payment-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/FREEPDB1}
    username: ${DATASOURCE_USERNAME:users}
    password: ${DATASOURCE_USERNAME:Va1722002}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: nbva-realm
  resource: nbva-app
  credentials:
    secret: wzHmmnm3gIAODdsKeokwf1EP848YSvVH
    username: nbva
    password: Va1722002
  bearer-only: true
  ssl-required: none
  use-resource-role-mappings: true
  cors: true

config:
  gateway:
    url: http://localhost:8762
  authenticate:
    url: ${AUTHENTICATE_URL:http://localhost:8081}