server:
  port: 8082
  servlet:
    context-path: /chat-service

spring:
  application:
      name: chat-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/nbva_shop
    username: nbva
    password: Va1722002
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:1521}
#      password: ${REDIS_PASSWORD:Mplis@123#@!}

config:
  gateway:
    url: http://localhost:8762